// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_WEB']!,
    appId: '1:187453366286:web:1ce69e26b42c56c5cb9c5f',
    messagingSenderId: '187453366286',
    projectId: 'ai-thumbnail-maker-f5d35',
    authDomain: 'ai-thumbnail-maker-f5d35.firebaseapp.com',
    storageBucket: 'ai-thumbnail-maker-f5d35.firebasestorage.app',
    measurementId: 'G-H5MBSJ3X2Z',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_ANDROID']!,
    appId: '1:187453366286:android:55b150cc63050ddacb9c5f',
    messagingSenderId: '187453366286',
    projectId: 'ai-thumbnail-maker-f5d35',
    storageBucket: 'ai-thumbnail-maker-f5d35.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_IOS']!,
    appId: '1:187453366286:ios:f612c71d7b1e4925cb9c5f',
    messagingSenderId: '187453366286',
    projectId: 'ai-thumbnail-maker-f5d35',
    storageBucket: 'ai-thumbnail-maker-f5d35.firebasestorage.app',
    iosBundleId: 'com.example.aiThumbnailMaker',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_MACOS']!,
    appId: '1:187453366286:ios:f612c71d7b1e4925cb9c5f',
    messagingSenderId: '187453366286',
    projectId: 'ai-thumbnail-maker-f5d35',
    storageBucket: 'ai-thumbnail-maker-f5d35.firebasestorage.app',
    iosBundleId: 'com.example.aiThumbnailMaker',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_WINDOWS']!,
    appId: '1:187453366286:web:9fdda6a07bb94ba0cb9c5f',
    messagingSenderId: '187453366286',
    projectId: 'ai-thumbnail-maker-f5d35',
    authDomain: 'ai-thumbnail-maker-f5d35.firebaseapp.com',
    storageBucket: 'ai-thumbnail-maker-f5d35.firebasestorage.app',
    measurementId: 'G-73FT2PQKJH',
  );
}
